Imported 3.11.0 release.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,6 @@
 ########################################################################
 #
-# $Id: configure.in,v 1.110 2013/02/15 18:01:29 mavrik Exp $
+# $Id: configure.in,v 1.112 2014/07/18 06:31:42 mavrik Exp $
 #
 ########################################################################
 
@@ -548,6 +548,84 @@ fi
 
 dnl ####################################################################
 dnl #
+dnl # Check for Python.
+dnl #
+dnl ####################################################################
+
+python_version=""
+python_version_major="0"
+python_version_floor="3"
+
+CheckPython()
+{
+  REFERENCE_PYTHON=${1}
+  if test ! -f "${REFERENCE_PYTHON}" ; then
+    return 1
+  fi
+  if test ! -x "${REFERENCE_PYTHON}" ; then
+    return 1
+  fi
+  python_version=`${REFERENCE_PYTHON} --version 2>&1 | awk '/^Python [[0-9]]/{print $2}'`
+  if test -n "${python_version}" ; then
+    python_version_major=`echo ${python_version} | awk -F. '{print $1}'`
+  fi
+  return 0
+}
+
+AC_MSG_CHECKING([for embedded Python support])
+AC_ARG_WITH(python,
+  [  --with-python=PATH      Embed Python using PATH as the reference version (disabled by default)],
+  [
+    dnl ################################################################
+    dnl #
+    dnl # Check the specified reference version only.
+    dnl #
+    dnl ################################################################
+    case `echo ${withval} | tr "A-Z" "a-z"` in
+    no)
+      use_python="0"
+      ;;
+    *)
+      use_python="1"
+      CheckPython "${withval}"
+      ;;
+    esac
+  ],
+  [
+    use_python="0"
+  ]
+)
+if test ${use_python} -ne 0 ; then
+  case "${target_os}" in
+  *mingw*)
+    AC_MSG_RESULT([this feature can not be enabled on this platform (aborting)])
+    exit 1
+    ;;
+  esac
+  AC_DEFINE(USE_EMBEDDED_PYTHON, 1, [Define to 1 if embedded Python 3.X.X support is enabled.])
+  if test -z "${python_version}" -o "${python_version_major}" -lt "${python_version_floor}" ; then
+    AC_MSG_RESULT(missing or incomplete)
+    echo
+    echo "Unable to locate required Python 3.X.X components. Use --with-python=PATH to"
+    echo "specify a known/different Python 3.X.X binary. In particular, Python's major"
+    echo "version number must be 3 or higher."
+    echo
+    exit 1
+  else
+    AC_MSG_RESULT(${python_version})
+    python_cflags=`${REFERENCE_PYTHON}-config --cflags`
+    python_incflags=`${REFERENCE_PYTHON}-config --includes`
+    python_libflags=`${REFERENCE_PYTHON}-config --ldflags`
+    AC_SUBST(python_cflags)
+    AC_SUBST(python_incflags)
+    AC_SUBST(python_libflags)
+  fi
+else
+  AC_MSG_RESULT(no)
+fi
+
+dnl ####################################################################
+dnl #
 dnl # Check whether or not KLEL release number is ok.
 dnl #
 dnl ####################################################################
@@ -555,6 +633,7 @@ dnl ####################################################################
 if test ${use_klel} -eq 1 ; then
   OLD_CFLAGS=${CFLAGS}
   OLD_LIBS=${LIBS}
+  OLD_LD_LIBRARY_PATH=${LD_LIBRARY_PATH} ; LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${kleldir}/lib" ; export LD_LIBRARY_PATH
   CFLAGS="${CFLAGS} ${klel_incflags} ${pcre_incflags}"
   LIBS="${LIBS} ${klel_libflags} ${pcre_libflags}"
   AC_MSG_CHECKING([whether or not KLEL release number is ok])
@@ -581,6 +660,7 @@ int main() { return (KlelGetReleaseNumber() >= 0x10100800) ? 0 : 1; }
   fi
   CFLAGS=${OLD_CFLAGS}
   LIBS=${OLD_LIBS}
+  LD_LIBRARY_PATH=${OLD_LD_LIBRARY_PATH} ; export LD_LIBRARY_PATH
 fi
 
 dnl ####################################################################
@@ -994,14 +1074,14 @@ AC_ARG_WITH(map-tools,
 )
 if test ${install_map} -ne 0 ; then
   AC_MSG_RESULT(yes)
-  map_list="ftimes-cat ftimes-cmp2dbi ftimes-cmp2diff ftimes-encoder ftimes-grabber ftimes-map2dbi ftimes-map2mac ftimes-proximo ftimes-sizimus ftimes-sortini ftimes-xformer ftimes-xpa hashcp tarmap zipmap"
+  map_list="ftimes-bimvl ftimes-cat ftimes-cmp2dbi ftimes-cmp2diff ftimes-encoder ftimes-grabber ftimes-map2dbi ftimes-map2mac ftimes-proximo ftimes-sizimus ftimes-sortini ftimes-xformer ftimes-xpa hashcp tarmap zipmap"
   doc_subdirs="${doc_subdirs} ${map_list}"
   doc_makefiles="${doc_makefiles} "`{ for item in ${map_list} ; do echo ${item} | sed 's,^,doc/,; s,$,/Makefile,;' ; done ; } | tr '\n' ' '`
   html_files="${html_files} "`{ for item in ${map_list} ; do echo ${item} | sed 's/$/.html/;' ; done ; } | tr '\n' ' '`
   man1_files="${man1_files} "`{ for item in ${map_list} ; do echo ${item} | sed 's/$/.1/;' ; done ; } | tr '\n' ' '`
-  tool_subdirs="${tool_subdirs} ftimes-cat ftimes-cmp2diff ftimes-encoder ftimes-grabber ftimes-proximo ftimes-sizimus ftimes-sortini ftimes-xformer ftimes-xpa hashcp map tarmap zipmap"
+  tool_subdirs="${tool_subdirs} ftimes-bimvl ftimes-cat ftimes-cmp2diff ftimes-encoder ftimes-grabber ftimes-proximo ftimes-sizimus ftimes-sortini ftimes-xformer ftimes-xpa hashcp map tarmap zipmap"
   tool_config_subdirs="${tool_config_subdirs} ftimes-cat ftimes-xpa hashcp tarmap"
-  tool_makefiles="${tool_makefiles} tools/ftimes-cat/Makefile tools/ftimes-cmp2diff/Makefile tools/ftimes-encoder/Makefile tools/ftimes-grabber/Makefile tools/ftimes-proximo/Makefile tools/ftimes-sizimus/Makefile tools/ftimes-sortini/Makefile tools/ftimes-xformer/Makefile tools/ftimes-xpa/Makefile tools/hashcp/Makefile tools/map/Makefile tools/tarmap/Makefile tools/zipmap/Makefile"
+  tool_makefiles="${tool_makefiles} tools/ftimes-bimvl/Makefile tools/ftimes-cat/Makefile tools/ftimes-cmp2diff/Makefile tools/ftimes-encoder/Makefile tools/ftimes-grabber/Makefile tools/ftimes-proximo/Makefile tools/ftimes-sizimus/Makefile tools/ftimes-sortini/Makefile tools/ftimes-xformer/Makefile tools/ftimes-xpa/Makefile tools/hashcp/Makefile tools/map/Makefile tools/tarmap/Makefile tools/zipmap/Makefile"
   additional_testdirs="${additional_testdirs} ftimes-encoder ftimes-xformer tarmap"
   test_makefiles="
 ${test_makefiles}
