Imported 3.5.0 release.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,6 @@
 ########################################################################
 #
-# $Id: configure.in,v 1.20 2004/04/22 05:24:58 mavrik Exp $
+# $Id: configure.in,v 1.32 2005/05/24 18:25:40 mavrik Exp $
 #
 ########################################################################
 
@@ -13,7 +13,7 @@ dnl ####################################################################
 AC_INIT(src/ftimes.c)
 AC_PREREQ(2.53)
 AC_CONFIG_HEADERS(src/config.h)
-AC_PREFIX_DEFAULT(/usr/local/integrity)
+AC_PREFIX_DEFAULT(/usr/local/ftimes)
 cgidir='${exec_prefix}/cgi'
 docdir='${exec_prefix}/doc'
 etcdir='${exec_prefix}/etc'
@@ -31,8 +31,8 @@ AC_CANONICAL_SYSTEM
 case "$target_os" in
 *aix*)
   OS_CFLAGS="-DUNIX"
-  AC_DEFINE(FTimes_AIX, 1, Define to 1 if the target OS is AIX.)
-  AC_DEFINE(USE_AP_SNPRINTF, 1, Define to 1 if snprintf() support is enabled.)
+  AC_DEFINE(FTimes_AIX, 1, [Define to 1 if the target OS is AIX.])
+  AC_DEFINE(USE_AP_SNPRINTF, 1, [Define to 1 if snprintf() support is enabled.])
   ap_srcs=ap_snprintf.c
   ap_incs=ap_snprintf.h
   extension=
@@ -42,20 +42,20 @@ case "$target_os" in
   ;;
 *bsd*)
   OS_CFLAGS="-DUNIX"
-  AC_DEFINE(FTimes_BSD, 1, Define to 1 if the target OS is BSD.)
+  AC_DEFINE(FTimes_BSD, 1, [Define to 1 if the target OS is BSD.])
   extension=
   AC_SUBST(extension)
   ;;
 *darwin*)
   OS_CFLAGS="-DUNIX"
-  AC_DEFINE(FTimes_MACOS, 1, Define to 1 if the target OS is MacOS.)
+  AC_DEFINE(FTimes_MACOS, 1, [Define to 1 if the target OS is MacOS.])
   extension=
   AC_SUBST(extension)
   ;;
 *hpux*)
   OS_CFLAGS="-DUNIX"
-  AC_DEFINE(FTimes_HPUX, 1, Define to 1 if the target OS is HP-UX.)
-  AC_DEFINE(USE_AP_SNPRINTF, 1, Define to 1 if snprintf() support is enabled.)
+  AC_DEFINE(FTimes_HPUX, 1, [Define to 1 if the target OS is HP-UX.])
+  AC_DEFINE(USE_AP_SNPRINTF, 1, [Define to 1 if snprintf() support is enabled.])
   ap_srcs=ap_snprintf.c
   ap_incs=ap_snprintf.h
   extension=
@@ -65,14 +65,21 @@ case "$target_os" in
   ;;
 *linux*)
   OS_CFLAGS="-DUNIX"
-  AC_DEFINE(FTimes_LINUX, 1, Define to 1 if the target OS is Linux.)
+  AC_DEFINE(FTimes_LINUX, 1, [Define to 1 if the target OS is Linux.])
   extension=
+  AC_SUBST(extension)
+  ;;
+*mingw32*)
+  OS_CFLAGS="-DWINNT -DWIN32 -DMINGW32"
+  LIBS="-lwsock32"
+  AC_DEFINE(FTimes_MINGW32, 1, [Define to 1 if the target OS is MinGW32.])
+  extension=.exe
   AC_SUBST(extension)
   ;;
 *solaris*)
   OS_CFLAGS="-DUNIX"
-  AC_DEFINE(FTimes_SOLARIS, 1, Define to 1 if the target OS is Solaris.)
-  AC_DEFINE(USE_AP_SNPRINTF, 1, Define to 1 if snprintf() support is enabled.)
+  AC_DEFINE(FTimes_SOLARIS, 1, [Define to 1 if the target OS is Solaris.])
+  AC_DEFINE(USE_AP_SNPRINTF, 1, [Define to 1 if snprintf() support is enabled.])
   ap_srcs=ap_snprintf.c
   ap_incs=ap_snprintf.h
   extension=
@@ -90,28 +97,28 @@ esac
 
 case $host_cpu in
 alpha*)
-  AC_DEFINE(K_CPU_ALPHA, 1, Define to 1 if the host cpu is alpha.)
+  AC_DEFINE(K_CPU_ALPHA, 1, [Define to 1 if the host cpu is alpha.])
   ;;
 amd64*)
-  AC_DEFINE(K_CPU_AMD64, 1, Define to 1 if the host cpu is amd64.)
+  AC_DEFINE(K_CPU_AMD64, 1, [Define to 1 if the host cpu is amd64.])
   ;;
 hppa*)
-  AC_DEFINE(K_CPU_HPPA, 1, Define to 1 if the host cpu is hppa.)
+  AC_DEFINE(K_CPU_HPPA, 1, [Define to 1 if the host cpu is hppa.])
   ;;
 ia64*)
-  AC_DEFINE(K_CPU_IA64, 1, Define to 1 if the host cpu is ia64.)
+  AC_DEFINE(K_CPU_IA64, 1, [Define to 1 if the host cpu is ia64.])
   ;;
 x86_64*)
-  AC_DEFINE(K_CPU_X86_64, 1, Define to 1 if the host cpu is x86_64.)
+  AC_DEFINE(K_CPU_X86_64, 1, [Define to 1 if the host cpu is x86_64.])
   ;;
 i?86*)
-  AC_DEFINE(K_CPU_I386, 1, Define to 1 if the host cpu is iX86.)
+  AC_DEFINE(K_CPU_I386, 1, [Define to 1 if the host cpu is iX86.])
   ;;
 powerpc*)
-  AC_DEFINE(K_CPU_POWERPC, 1, Define to 1 if the host cpu is powerpc.)
+  AC_DEFINE(K_CPU_POWERPC, 1, [Define to 1 if the host cpu is powerpc.])
   ;;
 sparc*)
-  AC_DEFINE(K_CPU_SPARC, 1, Define to 1 if the host cpu is sparc.)
+  AC_DEFINE(K_CPU_SPARC, 1, [Define to 1 if the host cpu is sparc.])
   ;;
 *)
   echo
@@ -181,6 +188,7 @@ dnl ####################################################################
 AC_C_CONST
 AC_TYPE_SIZE_T
 AC_CHECK_MEMBERS([struct stat.st_rdev])
+AC_SYS_LARGEFILE
 
 dnl ####################################################################
 dnl #
@@ -201,23 +209,27 @@ dnl # Check for OpenSSL.
 dnl #
 dnl ####################################################################
 
-LocateOpenSSLDirectory()
+CheckSSLComponents()
 {
-  if test -f "$1/include/openssl/ssl.h"; then
-    ssldir="$1"
-    return 0
-  fi
-  return 1
+  SSLDIR="$1"
+  INCLUDE_LIST="crypto.h err.h pem.h rand.h ssl.h x509.h"
+  for INCLUDE_FILE in ${INCLUDE_LIST}; do
+    if test ! -f "${SSLDIR}/include/openssl/${INCLUDE_FILE}"; then
+      return 1
+    fi
+  done
+  ssldir=${SSLDIR}
+  return 0
 }
 
 AC_MSG_CHECKING([for OpenSSL support])
 AC_ARG_WITH(ssl,
-  [  --with-ssl=DIR          Specify alternate OpenSSL location
+  [  --with-ssl=DIR          Use OpenSSL with includes and libs from [DIR]/include/openssl and [DIR]/lib
   --without-ssl           Disable OpenSSL support],
   [
     dnl ################################################################
     dnl #
-    dnl # Check the specified localtion only.
+    dnl # Check the specified location only.
     dnl #
     dnl ################################################################
     case `echo $withval | tr "A-Z" "a-z"` in
@@ -226,7 +238,7 @@ AC_ARG_WITH(ssl,
       ;;
     *)
       use_ssl=1
-      LocateOpenSSLDirectory "$withval"
+      CheckSSLComponents "$withval"
       ;;
     esac
   ],
@@ -237,31 +249,120 @@ AC_ARG_WITH(ssl,
     dnl #
     dnl ################################################################
     use_ssl=1
-    for basedir in /usr /usr/local /usr/pkg /opt; do
+    for basedir in /usr /usr/local /usr/pkg /opt /opt/local; do
       for dir in $basedir $basedir/openssl $basedir/ssl; do
-        LocateOpenSSLDirectory $dir && break 2
+        CheckSSLComponents $dir && break 2
       done
     done
   ]
 )
 if test $use_ssl -ne 0; then
-  AC_DEFINE(USE_SSL, 1, Define to 1 if OpenSSL support is enabled.)
+  AC_DEFINE(USE_SSL, 1, [Define to 1 if OpenSSL support is enabled.])
   if test -z "$ssldir"; then
-    AC_MSG_RESULT(missing)
+    AC_MSG_RESULT(missing or incomplete)
     echo
-    echo "Unable to locate OpenSSL. Use --with-ssl=DIR to specify a location."
+    echo "Unable to locate required OpenSSL components. Use --with-ssl=DIR"
+    echo "to specify a known or different location. The files that must exist"
+    echo "for this check to pass are:"
+    echo
+    echo "  DIR/include/openssl/crypto.h"
+    echo "  DIR/include/openssl/err.h"
+    echo "  DIR/include/openssl/pem.h"
+    echo "  DIR/include/openssl/rand.h"
+    echo "  DIR/include/openssl/ssl.h"
+    echo "  DIR/include/openssl/x509.h"
     echo
     exit 1
   else
     AC_MSG_RESULT($ssldir)
     ssl_srcs=ssl.c
     ssl_incs="ssl.h ssl-pool.h"
-    sslincflags="-I$ssldir/include"
-    ssllibflags="-L$ssldir/lib -lssl -lcrypto"
+    ssl_incflags="-I$ssldir/include"
+    ssl_libflags="-L$ssldir/lib -lssl -lcrypto"
     AC_SUBST(ssl_srcs)
     AC_SUBST(ssl_incs)
-    AC_SUBST(sslincflags)
-    AC_SUBST(ssllibflags)
+    AC_SUBST(ssl_incflags)
+    AC_SUBST(ssl_libflags)
+  fi
+else
+  AC_MSG_RESULT(check explicitly disabled)
+fi
+
+dnl ####################################################################
+dnl #
+dnl # Check for PCRE.
+dnl #
+dnl ####################################################################
+
+CheckPCREComponents()
+{
+  PCREDIR="$1"
+  INCLUDE_LIST="pcre.h"
+  for INCLUDE_FILE in ${INCLUDE_LIST}; do
+    if test ! -f "${PCREDIR}/include/${INCLUDE_FILE}"; then
+      return 1
+    fi
+  done
+  pcredir=${PCREDIR}
+  return 0
+}
+
+AC_MSG_CHECKING([for PCRE support])
+AC_ARG_WITH(pcre,
+  [  --with-pcre=DIR         Use PCRE with includes and libs from [DIR]/include and [DIR]/lib
+  --without-pcre          Disable PCRE support],
+  [
+    dnl ################################################################
+    dnl #
+    dnl # Check the specified location only.
+    dnl #
+    dnl ################################################################
+    case `echo $withval | tr "A-Z" "a-z"` in
+    no)
+      use_pcre=0
+      ;;
+    *)
+      use_pcre=1
+      CheckPCREComponents "$withval"
+      ;;
+    esac
+  ],
+  [
+    dnl ################################################################
+    dnl #
+    dnl # Search common PCRE locations.
+    dnl #
+    dnl ################################################################
+    use_pcre=1
+    for basedir in /usr /usr/local /usr/pkg /opt /opt/local; do
+      for dir in $basedir $basedir/pcre; do
+        CheckPCREComponents $dir && break 2
+      done
+    done
+  ]
+)
+if test $use_pcre -ne 0; then
+  AC_DEFINE(USE_PCRE, 1, [Define to 1 if PCRE support is enabled.])
+  if test -z "$pcredir"; then
+    AC_MSG_RESULT(missing or incomplete)
+    echo
+    echo "Unable to locate required PCRE components. Use --with-pcre=DIR to"
+    echo "specify a known or different location. The files that must exist for"
+    echo "this check to pass are:"
+    echo
+    echo "  DIR/include/pcre.h"
+    echo
+    exit 1
+  else
+    AC_MSG_RESULT($pcredir)
+    pcre_srcs=
+    pcre_incs=
+    pcre_incflags="-I$pcredir/include"
+    pcre_libflags="-L$pcredir/lib -lpcre"
+    AC_SUBST(pcre_srcs)
+    AC_SUBST(pcre_incs)
+    AC_SUBST(pcre_incflags)
+    AC_SUBST(pcre_libflags)
   fi
 else
   AC_MSG_RESULT(check explicitly disabled)
@@ -273,15 +374,29 @@ dnl # Check whether or not to include XMagic.
 dnl #
 dnl ####################################################################
 
-AC_MSG_CHECKING(whether to include XMagic support)
+AC_MSG_CHECKING([whether to include XMagic support])
 AC_ARG_ENABLE(xmagic,
   [  --enable-xmagic         Enable XMagic support (disabled by default)],
   [ AC_MSG_RESULT(yes)
-    AC_DEFINE(USE_XMAGIC, 1, Define to 1 if XMagic support is enabled.)
+    AC_DEFINE(USE_XMAGIC, 1, [Define to 1 if XMagic support is enabled.])
     xmagic_srcs=xmagic.c
     xmagic_incs=xmagic.h
     AC_SUBST(xmagic_srcs)
     AC_SUBST(xmagic_incs) ],
+  [ AC_MSG_RESULT(no) ]
+)
+
+dnl ####################################################################
+dnl #
+dnl # Check whether or not to compile using pre-mem{set,cpy} MD5 logic.
+dnl #
+dnl ####################################################################
+
+AC_MSG_CHECKING([whether to compile using pre-mem{set,cpy} MD5 logic])
+AC_ARG_ENABLE(md5-pre-msmc,
+  [  --enable-md5-pre-msmc   Enable pre-mem{set,cpy} MD5 logic (disabled by default)],
+  [ AC_MSG_RESULT(yes)
+    AC_DEFINE(MD5_PRE_MEMSET_MEMCPY, 1, [Define to 1 if pre-mem{set,cpy} MD5 logic is enabled.])],
   [ AC_MSG_RESULT(no) ]
 )
 
@@ -451,10 +566,21 @@ dnl ####################################################################
 AC_CONFIG_FILES(
   [
     Makefile
+    Mk/common.mk
+    Mk/common-macros.mk
+    Mk/common-tests.mk
     $server_makefiles
     doc/Makefile
     etc/Makefile
     src/Makefile
+    tests/Makefile
+    tests/common/Makefile
+    tests/common/dig/Makefile
+    tests/common/dig/test_1/Makefile
+    tests/common/dig/test_2/Makefile
+    tests/common/map/Makefile
+    tests/common/map/test_1/Makefile
+    tests/common/map/test_2/Makefile
     $tool_makefiles
   ]
 )
