Imported 3.8.0 release.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,10 +1,10 @@
 ########################################################################
 #
-# $Id: Makefile.in,v 1.17 2006/05/26 19:38:24 mavrik Exp $
+# $Id: Makefile.in,v 1.22 2007/02/23 00:22:35 mavrik Exp $
 #
 ########################################################################
 #
-# Copyright 2000-2006 Klayton Monroe, All Rights Reserved.
+# Copyright 2000-2007 Klayton Monroe, All Rights Reserved.
 #
 ########################################################################
 #
@@ -12,59 +12,47 @@
 #
 ########################################################################
 
-#.SILENT:
+CONFIGURE_FILES=\
+Makefile\
+config.cache\
+config.log\
+config.status\
+configure.lineno
 
-prefix			= @prefix@
-exec_prefix		= @exec_prefix@
-srcdir			= @srcdir@
-VPATH			= ${srcdir}
+srcdir=@srcdir@
 
-INSTALL			= @INSTALL@
+SUBDIRS=@server_subdirs@ doc etc src tools tests # Note: Keep the tests subdir last.
 
-SUBDIRS			=\
-			@server_subdirs@\
-			doc\
-			etc\
-			src\
-			tests\
-			tools
+SUBDIR_MAKE=cd $${cwd}/$${subdir} && ${MAKE} $@
 
-CONFIGURE_FILES		=\
-			Makefile\
-			config.cache\
-			config.log\
-			config.status\
-			configure.lineno
+SUBDIR_TRACE=echo "===> $${subdir}"
 
-all:
-	@cwd=`pwd`; for i in ${SUBDIRS}; do\
-		echo '===>' $${i} && cd $${cwd}/$${i} && ${MAKE} $@ ;\
-	done
+TARMAP_LINKS=\
+ap_snprintf.c\
+ap_snprintf.h\
+ktypes.h\
+md5.c\
+md5.h\
+sha1.c\
+sha1.h
 
-test:
-	@cwd=`pwd`; for i in ${SUBDIRS}; do\
-		echo '===>' $${i} && cd $${cwd}/$${i} && ${MAKE} $@ ;\
-	done
-
-install:
-	@umask 22; if [ ! -d ${prefix} ]; then mkdir -p ${prefix}; fi
-	@cwd=`pwd`; for i in ${SUBDIRS}; do\
-		echo '===>' $${i} && cd $${cwd}/$${i} && ${MAKE} $@ ;\
-	done
-
-clean:
-	@cwd=`pwd`; for i in ${SUBDIRS}; do\
-		echo '===>' $${i} && cd $${cwd}/$${i} && ${MAKE} $@ ;\
+all clean install test:
+	@cwd=`pwd` ; for subdir in ${SUBDIRS} "end-of-list" ; do\
+		if test $${subdir} != "end-of-list" ; then\
+			${SUBDIR_TRACE} && ${SUBDIR_MAKE} ;\
+		fi ;\
 	done
 
 clean-all:
-	@cwd=`pwd`; for i in ${SUBDIRS}; do\
-		echo '===>' $${i} && cd $${cwd}/$${i} && ${MAKE} $@ ;\
+	@cwd=`pwd` ; for subdir in ${SUBDIRS} "end-of-list" ; do\
+		if test $${subdir} != "end-of-list" ; then\
+			${SUBDIR_TRACE} && ${SUBDIR_MAKE} ;\
+		fi ;\
 	done
 	rm -f ${CONFIGURE_FILES}
 
-auto:
-	@if [ "${srcdir}" != `echo "@""srcdir""@"` ]; then\
+auto: mk-links
+	@if [ "${srcdir}" != "@""srcdir""@" ]; then\
 		echo "";\
 		echo "ERROR: The 'auto' target is for release building, and is not VPATH";\
 		echo "       aware. To exercise this target, get into the project's root";\
@@ -73,6 +61,32 @@ auto:
 		exit 1;\
 	fi
 	autoconf && autoheader ; rm -rf autom4te.cache src/config.h.in~
+
+mk-links:
+	@if [ "${srcdir}" != "@""srcdir""@" ]; then\
+		echo "";\
+		echo "ERROR: The 'mk-links' target is for release building, and is not VPATH";\
+		echo "       aware. To exercise this target, get into the project's root";\
+		echo "       directory and run: 'make -f Makefile.in mk-links'";\
+		echo "";\
+		exit 1;\
+	fi
+	@for file in ${TARMAP_LINKS}; do\
+		( cd tools/tarmap && if [ ! -L $${file} ] ; then ln -s -f ../../src/$${file} $${file} ; fi ) ;\
+	done
+
+rm-links:
+	@if [ "${srcdir}" != "@""srcdir""@" ]; then\
+		echo "";\
+		echo "ERROR: The 'rm-links' target is for release building, and is not VPATH";\
+		echo "       aware. To exercise this target, get into the project's root";\
+		echo "       directory and run: 'make -f Makefile.in rm-links'";\
+		echo "";\
+		exit 1;\
+	fi
+	@for file in ${TARMAP_LINKS}; do\
+		( cd tools/tarmap && if [ -L $${file} ] ; then rm -f $${file} ; fi ) ;\
+	done
 
 atar: ctar dtar
 
