Imported 3.1.0 release.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,6 +1,6 @@
 ########################################################################
 #
-# $Id: Makefile.in,v 1.2 2002/01/18 15:54:07 mavrik Exp $
+# $Id: Makefile.in,v 1.4 2002/08/21 18:28:13 mavrik Exp $
 #
 ########################################################################
 #
@@ -17,42 +17,51 @@
 
 prefix			= @prefix@
 exec_prefix		= @exec_prefix@
+srcdir			= @srcdir@
+VPATH			= ${srcdir}
 
 INSTALL			= @INSTALL@
-RM			= rm -f
-
 SUBS			=\
 			cgi\
 			doc\
 			etc\
 			src
+CONFIGURE_FILES		=\
+			Makefile\
+			config.cache\
+			config.log\
+			config.status
 
 all:
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
+	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $${i} '>>> Status=Open'; cd $${cwd}/$${i}; make $@; echo '<<<' $${i} '>>> Status=Done'; done
 
 install:
 	umask 22; if [ ! -d ${prefix} ]; then mkdir ${prefix}; fi
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
+	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $${i} '>>> Status=Open'; cd $${cwd}/$${i}; make $@; echo '<<<' $${i} '>>> Status=Done'; done
 
 clean:
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
+	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $${i} '>>> Status=Open'; cd $${cwd}/$${i}; make $@; echo '<<<' $${i} '>>> Status=Done'; done
 
-clean-all: clean-auto
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
+clean-all:
+	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $${i} '>>> Status=Open'; cd $${cwd}/$${i}; make $@; echo '<<<' $${i} '>>> Status=Done'; done
+	rm -f ${CONFIGURE_FILES}
 
-clean-auto:
-	${RM} config.cache config.status config.log Makefile
+auto:
+	@if [ "${srcdir}" != `echo "@""srcdir""@"` ]; then\
+		echo "";\
+		echo "ERROR: The 'auto' target is for release building, and is not VPATH";\
+		echo "       aware. To exercise this target, get into the project's root";\
+		echo "       directory and run: 'make -f Makefile.in auto'";\
+		echo "";\
+		exit 1;\
+	fi
+	autoconf; autoheader --localdir=src configure.in > src/config.h.in
 
-dist-clean: clean-auto
-	${RM} configure
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
-
-auto: configure.in Makefile.in src/Makefile.in
-	autoconf
-	autoheader --localdir=src configure.in > src/config.h.in
+atar: ctar dtar
 
 ctar:
 	@cwd=`pwd`; dir=`basename $$cwd`; tar -C ../ -zcf "../$$dir-current.tgz" $$dir
 
 dtar:
 	@cwd=`pwd`; dir=`basename $$cwd`; ts=`date "+%Y-%m-%d"`; tar -C ../ -zcf "../$$dir-$$ts.tgz" $$dir
+
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,137 +1,262 @@
+########################################################################
 #
-# $Id: configure.in,v 1.1.1.1 2002/01/18 03:16:22 mavrik Exp $
+# $Id: configure.in,v 1.6 2002/09/20 17:46:02 mavrik Exp $
 #
-dnl Process this file with autoconf to produce a configure script.
+########################################################################
+
+dnl ####################################################################
+dnl #
+dnl # Initialize.
+dnl #
+dnl ####################################################################
+
 AC_INIT(src/ftimes.c)
 AC_CONFIG_HEADER(src/config.h)
-
 AC_PREFIX_DEFAULT(/usr/local/integrity)
 cgidir='${exec_prefix}/cgi'
 docdir='${exec_prefix}/doc'
 etcdir='${exec_prefix}/etc'
 logdir='${exec_prefix}/log'
+mandir='${exec_prefix}/man'
 rundir='${exec_prefix}/run'
 AC_SUBST(cgidir)
 AC_SUBST(docdir)
 AC_SUBST(etcdir)
 AC_SUBST(logdir)
+AC_SUBST(mandir)
 AC_SUBST(rundir)
 
 AC_CANONICAL_SYSTEM
-
-dnl Checks for programs.
-AC_PROG_CC
-if test "$GCC" = "yes"; then CFLAGS="$CFLAGS -Wall"; fi
-AC_PROG_INSTALL
-AC_PROG_MAKE_SET
-
 case "$target_os" in
-
-aix*)
+*aix*)
         AC_DEFINE(FTimes_UNIX)
         AC_DEFINE(FTimes_AIX)
         AC_DEFINE(USE_AP_SNPRINTF)
         ap_srcs=ap_snprintf.c
         ap_incs=ap_snprintf.h
+        extension=
         AC_SUBST(ap_srcs)
         AC_SUBST(ap_incs)
+        AC_SUBST(extension)
         ;;
-
 *bsd*)
         AC_DEFINE(FTimes_UNIX)
         AC_DEFINE(FTimes_BSD)
+        extension=
+        AC_SUBST(extension)
         ;;
-
-linux*)
+*darwin*)
+        AC_DEFINE(FTimes_UNIX)
+        AC_DEFINE(FTimes_MACOS)
+        extension=
+        AC_SUBST(extension)
+        ;;
+*linux*)
         AC_DEFINE(FTimes_UNIX)
         AC_DEFINE(FTimes_LINUX)
+        extension=
+        AC_SUBST(extension)
         ;;
-
-solaris*)
+*solaris*)
         AC_DEFINE(FTimes_UNIX)
         AC_DEFINE(FTimes_SOLARIS)
         AC_DEFINE(USE_AP_SNPRINTF)
         ap_srcs=ap_snprintf.c
         ap_incs=ap_snprintf.h
+        extension=
         AC_SUBST(ap_srcs)
         AC_SUBST(ap_incs)
+        AC_SUBST(extension)
         ;;
-
+*)
+        echo
+        echo "The target operating system, $target_os, is not currently supported."
+        echo
+        exit
+        ;;
 esac
 
-AC_MSG_CHECKING(whether to compile with XMagic)
-AC_ARG_ENABLE(xmagic,
-  [  --enable-xmagic         Enable XMagic support ],
+case $host_cpu in
+alpha*)
+        AC_DEFINE(K_CPU_ALPHA)
+	;;
+i?86*)
+        AC_DEFINE(K_CPU_I386)
+	;;
+powerpc*)
+        AC_DEFINE(K_CPU_POWERPC)
+	;;
+sparc*)
+        AC_DEFINE(K_CPU_SPARC)
+	;;
+*)
+        echo
+        echo "The target cpu, $host_cpu, is not currently supported."
+        echo
+        exit
+        ;;
+esac
 
-  [ AC_MSG_RESULT(yes)
-    AC_DEFINE(USE_XMAGIC)
-    xmagic_srcs=xmagic.c
-    xmagic_incs=xmagic.h
-    AC_SUBST(xmagic_srcs)
-    AC_SUBST(xmagic_incs) ],
+dnl ####################################################################
+dnl #
+dnl # Check for programs.
+dnl #
+dnl ####################################################################
 
-  [ AC_MSG_RESULT(no) ]
-)
+AC_PROG_CC
+if test "$GCC" = "yes"; then CFLAGS="$CFLAGS -Wall"; fi
+AC_PROG_INSTALL
+AC_PROG_MAKE_SET
 
-AC_MSG_CHECKING(whether to compile with SSL)
-AC_ARG_ENABLE(ssl,
-  [  --enable-ssl            Enable SSL support ],
+dnl ####################################################################
+dnl #
+dnl # Check for libraries.
+dnl #
+dnl ####################################################################
 
-  [ AC_MSG_RESULT(yes)
-    AC_DEFINE(USE_SSL)
-      dnl Check for SSL directories.
-      AC_MSG_CHECKING([for SSL directory])
-      for dir in /usr/local/ssl /usr/lib/ssl /usr/pkg /usr/local /usr; do
-          ssldir="$dir"
-          if test -f "$dir/include/openssl/ssl.h"; then
-              AC_DEFINE(HAVE_OPENSSL)
-              break
-          fi
-          if test -f "$dir/include/ssl.h"; then
-              break
-          fi
-      done
-      AC_MSG_RESULT($ssldir)
-      AC_SUBST(ssldir)
-      AC_DEFINE_UNQUOTED(ssldir, "$ssldir")
-      ssl_srcs=ssl.c
-      ssl_incs=ssl.h
-      AC_SUBST(ssl_srcs)
-      AC_SUBST(ssl_incs)
-      sslincflags="-I$ssldir/include"
-      AC_SUBST(sslincflags)
-      ssllibflags="-L$ssldir/lib -lssl -lcrypto"
-      AC_SUBST(ssllibflags)
-      
-      dnl Check for RSAref library.
-      AC_MSG_CHECKING([for RSAref library])
-      saved_LIBS="$LIBS"
-      LIBS="$saved_LIBS -lRSAglue -lrsaref"
-      AC_TRY_LINK([], [], [AC_MSG_RESULT(yes); ], [AC_MSG_RESULT(no)]; LIBS="$saved_LIBS")
-  ],
-
-  [ AC_MSG_RESULT(no) ]
-)
-
-dnl Checks for standard libraries.
 AC_CHECK_LIB(nsl, gethostbyname)
 AC_CHECK_LIB(socket, socket)
 
-dnl Checks for header files.
+dnl ####################################################################
+dnl #
+dnl # Check for header files.
+dnl #
+dnl ####################################################################
+
 AC_HEADER_DIRENT
 AC_HEADER_STDC
 AC_CHECK_HEADERS(fcntl.h limits.h sys/time.h unistd.h unistd.h sys/select.h)
 
-dnl Checks for typedefs, structures, and compiler characteristics.
+dnl ####################################################################
+dnl #
+dnl # Check for typedefs, structures, and compiler characteristics.
+dnl #
+dnl ####################################################################
+
 AC_C_CONST
 AC_TYPE_SIZE_T
 AC_STRUCT_ST_RDEV
 AC_HEADER_TIME
 AC_TYPE_UID_T
 
-dnl Checks for library functions.
+dnl ####################################################################
+dnl #
+dnl # Check for library functions.
+dnl #
+dnl ####################################################################
+
 AC_FUNC_MEMCMP
 AC_FUNC_STRFTIME
 AC_CHECK_FUNCS(gettimeofday socket strerror strstr uname snprintf vsnprintf)
+
+dnl ####################################################################
+dnl #
+dnl # Check for OpenSSL.
+dnl #
+dnl ####################################################################
+
+LocateOpenSSLDirectory()
+{
+  if test -f "$1/include/openssl/ssl.h"; then
+    ssldir="$1"
+    return 0
+  fi
+  return 1
+}
+
+AC_MSG_CHECKING([for OpenSSL support])
+AC_ARG_WITH(ssl,
+  [  --with-ssl=DIR          Specify alternate OpenSSL location
+  --without-ssl           Disable OpenSSL support (same as --with-ssl=no)],
+  [
+    dnl ################################################################
+    dnl #
+    dnl # Check the specified localtion only.
+    dnl #
+    dnl ################################################################
+    case `echo $withval | tr "A-Z" "a-z"` in
+    no)
+      use_ssl=0
+      ;;
+    *)
+      use_ssl=1
+      LocateOpenSSLDirectory "$withval"
+      ;;
+    esac
+  ],
+  [
+    dnl ################################################################
+    dnl #
+    dnl # Search common OpenSSL locations.
+    dnl #
+    dnl ################################################################
+    use_ssl=1
+    for basedir in /usr /usr/local /usr/pkg /opt; do
+      for dir in $basedir $basedir/openssl $basedir/ssl; do
+        LocateOpenSSLDirectory $dir && break 2
+      done
+    done
+  ]
+)
+if test $use_ssl -ne 0; then
+  AC_DEFINE(USE_SSL)
+  if test -z "$ssldir"; then
+    AC_MSG_RESULT(missing)
+    echo
+    echo "Unable to locate OpenSSL. Use --with-ssl=DIR to specify a location."
+    echo
+    exit 1
+  else
+    AC_MSG_RESULT($ssldir)
+    ssl_srcs=ssl.c
+    ssl_incs="ssl.h ssl-pool.h"
+    sslincflags="-I$ssldir/include"
+    ssllibflags="-L$ssldir/lib -lssl -lcrypto"
+    AC_SUBST(ssl_srcs)
+    AC_SUBST(ssl_incs)
+    AC_SUBST(sslincflags)
+    AC_SUBST(ssllibflags)
+  fi
+else
+  AC_MSG_RESULT(check explicitly disabled)
+fi
+
+dnl ####################################################################
+dnl #
+dnl # Check whether or not to include XMagic.
+dnl #
+dnl ####################################################################
+
+AC_MSG_CHECKING(whether to include XMagic support)
+AC_ARG_ENABLE(xmagic,
+  [  --enable-xmagic         Enable XMagic support ],
+  [ AC_MSG_RESULT(yes)
+    AC_DEFINE(USE_XMAGIC)
+    xmagic_srcs=xmagic.c
+    xmagic_incs=xmagic.h
+    AC_SUBST(xmagic_srcs)
+    AC_SUBST(xmagic_incs) ],
+  [ AC_MSG_RESULT(no) ]
+)
+
+dnl ####################################################################
+dnl #
+dnl # Check whether or not to enable block/character device includes.
+dnl #
+dnl ####################################################################
+
+AC_MSG_CHECKING(whether to enable block/character device includes)
+AC_ARG_ENABLE(devices,
+  [  --enable-devices        Enable block/character device includes ],
+  [ AC_MSG_RESULT(yes)
+    AC_DEFINE(ENABLE_BLK_CHR_DEVICE_INCLUDES) ],
+  [ AC_MSG_RESULT(no) ]
+)
+
+dnl ####################################################################
+dnl #
+dnl # Create Makefiles.
+dnl #
+dnl ####################################################################
 
 AC_OUTPUT(Makefile cgi/Makefile doc/Makefile etc/Makefile src/Makefile)
diff --git a/doc/Makefile.in b/doc/Makefile.in
--- a/doc/Makefile.in
+++ b/doc/Makefile.in
@@ -1,6 +1,6 @@
 ########################################################################
 #
-# $Id: Makefile.in,v 1.1.1.1 2002/01/18 03:16:26 mavrik Exp $
+# $Id: Makefile.in,v 1.3 2002/05/20 18:54:37 mavrik Exp $
 #
 ########################################################################
 #
@@ -18,30 +18,55 @@
 prefix			= @prefix@
 exec_prefix		= @exec_prefix@
 docdir			= @docdir@
+mandir			= @mandir@
+man1dir			= ${mandir}/man1
+srcdir			= @srcdir@
+VPATH			= ${srcdir}
 
 INSTALL			= @INSTALL@
 SUBS			= ftimes
 ALL_HTML_FILES		= ftimes.html
 ALL_MAN1_FILES		= ftimes.1
-ALL_TEXT_FILES		=
-ALL_FILES		= ${ALL_HTML_FILES} ${ALL_MAN1_FILES} ${ALL_TEXT_FILES}
 
 all:
 
-install: ${DST_FILES}
+install: ${ALL_HTML_FILES} ${ALL_MAN1_FILES}
 	umask 22; if [ ! -d ${docdir} ]; then mkdir ${docdir}; fi
-	for i in ${ALL_FILES}; do ${INSTALL} -m 644 $$i ${docdir}; done
+	for i in ${ALL_HTML_FILES}; do\
+		if [ -f ${srcdir}/$${i} ]; then file=${srcdir}/$${i}; else file=$${i}; fi;\
+		${INSTALL} -m 644 $${file} ${docdir};\
+	done
+	umask 22; if [ ! -d ${man1dir} ]; then mkdir -p ${man1dir}; fi
+	for i in ${ALL_MAN1_FILES}; do\
+		if [ -f ${srcdir}/$${i} ]; then file=${srcdir}/$${i}; else file=$${i}; fi;\
+		${INSTALL} -m 644 $${file} ${man1dir};\
+	done
 
 clean:
 
-clean-auto: clean
+clean-all: clean
 	rm -f Makefile
 
-clean-all: clean-auto
-
 dist:
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
+	@if [ "${srcdir}" != `echo "@""srcdir""@"` ]; then\
+		echo "";\
+		echo "ERROR: The 'dist' target is for release building, and is not VPATH";\
+		echo "       aware. To exercise this target, get into the project's doc";\
+		echo "       directory and run: 'make -f Makefile.in dist'";\
+		echo "";\
+		exit 1;\
+	fi
+	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $${i} '>>> Status=Open'; cd $${cwd}/$${i}; make install; echo '<<<' $${i} '>>> Status=Done'; done
 
-dist-clean: clean-all
-	rm -f ${ALL_FILES}
-	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $$i '>>>'; cd $$cwd/$$i; make $@; done
+dist-clean:
+	@if [ "${srcdir}" != `echo "@""srcdir""@"` ]; then\
+		echo "";\
+		echo "ERROR: The 'dist-clean' target is for release building, and is not";\
+		echo "       VPATH aware. To exercise this target, get into the project's";\
+		echo "       doc directory and run: 'make -f Makefile.in dist-clean'";\
+		echo "";\
+		exit 1;\
+	fi
+	@cwd=`pwd`; for i in ${SUBS}; do echo '<<<' $${i} '>>> Status=Open'; cd $${cwd}/$${i}; make clean-all; echo '<<<' $${i} '>>> Status=Done'; done
+	rm -f Makefile ${ALL_HTML_FILES} ${ALL_MAN1_FILES}
+
